"""Reports page: list and view HTML reports generated by src/reporter.py."""

from __future__ import annotations

import asyncio
from concurrent.futures import ThreadPoolExecutor
from datetime import datetime, timedelta, timezone
from pathlib import Path

from fastapi import APIRouter, Request
from fastapi.responses import FileResponse, HTMLResponse

from src.main import run_all
from web.deps import templates

router = APIRouter()

_REPORTS_DIR = Path(__file__).parent.parent.parent / "data" / "reports"
_executor = ThreadPoolExecutor(max_workers=1, thread_name_prefix="reports")
_gen_status: dict[str, str] = {"status": "idle", "msg": ""}


def _list_reports() -> list[dict]:
    if not _REPORTS_DIR.exists():
        return []
    files = sorted(_REPORTS_DIR.glob("*.html"), key=lambda f: f.stat().st_mtime, reverse=True)
    result = []
    for f in files:
        mtime = f.stat().st_mtime
        dt = datetime.fromtimestamp(mtime, tz=timezone.utc) + timedelta(hours=8)
        size_kb = f.stat().st_size / 1024
        result.append({
            "filename": f.name,
            "datetime": dt.strftime("%Y-%m-%d %H:%M"),
            "size": f"{size_kb:.1f} KB",
        })
    return result


async def _generate_report_async() -> None:
    _gen_status["status"] = "running"
    loop = asyncio.get_event_loop()
    try:
        await loop.run_in_executor(_executor, run_all)
        _gen_status["status"] = "done"
        _gen_status["msg"] = ""
    except Exception as exc:
        _gen_status["status"] = "error"
        _gen_status["msg"] = str(exc)[:80]


@router.get("/reports", response_class=HTMLResponse)
def reports_page(request: Request) -> HTMLResponse:
    return templates.TemplateResponse(
        request,
        "reports.html",
        {"reports": _list_reports(), "gen_status": _gen_status},
    )


@router.get("/reports/view/{filename}")
def view_report(filename: str) -> FileResponse:
    resolved = (_REPORTS_DIR / filename).resolve()
    if not resolved.is_relative_to(_REPORTS_DIR.resolve()) or resolved.suffix != ".html" or not resolved.exists():
        return HTMLResponse("报表不存在", status_code=404)
    return FileResponse(resolved, media_type="text/html")


@router.post("/reports/generate", response_class=HTMLResponse)
async def generate_report(request: Request) -> HTMLResponse:
    if _gen_status.get("status") != "running":
        asyncio.create_task(_generate_report_async())
    return templates.TemplateResponse(
        request,
        "_partials/report_gen_status.html",
        {"gen_status": {"status": "running", "msg": ""}},
    )


@router.get("/reports/gen-status", response_class=HTMLResponse)
def gen_status(request: Request) -> HTMLResponse:
    ctx = {"gen_status": _gen_status, "reports": _list_reports()}
    if _gen_status["status"] in ("done", "error"):
        # Return full reports list refreshed
        return templates.TemplateResponse(request, "_partials/reports_list.html", ctx)
    return templates.TemplateResponse(request, "_partials/report_gen_status.html", ctx)
